dist: bionic
sudo: false

language: c++

compiler:
    - gcc

env:
    - BUILD=DEBUG
    - BUILD=RELEASE

before_script:
    - mkdir -p BUILD/$BUILD/BUILD && cd BUILD/$BUILD/BUILD
    - |
        cmake -DCMAKE_BUILD_TYPE=$BUILD \
              -DCMAKE_INSTALL_PREFIX=.. \
              -DFTL_BUILD_TESTS=ON      \
              -DFTL_BUILD_EXAMPLES=ON

script:
    - make -j 4 && ctest --output-on-failure && make install
