dist: trusty
sudo: false

language: c++

compiler:
    - gcc

cache:
    directories:
        - DEPENDS

env:
    - BUILD=DEBUG
    - BUILD=RELEASE

install:
    - mkdir -p DEPENDS && cd DEPENDS
    - export GTEST_ROOT=`pwd`/googletest-release-1.8.0/INSTALL
    - export GMOCK_ROOT=$GTEST_ROOT
    - | # Build Google Test
        if [ ! -d $GTEST_ROOT ]; then
            wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
            tar -xzf release-1.8.0.tar.gz && cd googletest-release-1.8.0
            mkdir BUILD && cd BUILD
            cmake .. -DCMAKE_INSTALL_PREFIX=$GTEST_ROOT -DCMAKE_CXX_STANDARD=11
            make -j 4 && make install
            cd ../..
            rm -rf release-1.8.0.tar.gz googletest-release-1.8.0/BUILD
        fi
    - cd ..

before_script:
    - mkdir -p BUILD/$BUILD/BUILD && cd BUILD/$BUILD/BUILD
    - cmake ../../.. -DCMAKE_BUILD_TYPE=$BUILD -DCMAKE_INSTALL_PREFIX=..

script:
    - make -j 4 && ctest --output-on-failure && make install
