dist: bionic
sudo: false

language: c++

compiler:
    - gcc

addons:
    coverity_scan:
        project:
            name: "janweinstock/ftl"
            description: "An x86 code generator library for dynamic binary translation"
        notification_email: "jan.weinstock@rwth-aachen.de"
        build_command: "make"
        branch_pattern: "coverity"

env:
    global:
        - secure: "Xm55GJ5Kz/dQUb/CdKXD2HBSpP2QlFC2w4B5MmaatKBslaVIjMW0/zBultL/2ClldCt029Nu3cU1RxKfrLbMZRnJRMB9HK6GtVmdtVy2VgNmdPbvcpHksnP6YNb5guCiUE4Jj0RDZD5IiOkRfwfJovfQnqhbrRBmMwAxHfHBtKIKh5YjtIU4Q1/dLMtwO6mgSBMfy9K1+XbSGD5BZu7c8KrpwyU63v8p/k0XjeZodLFC31cikhG6qHdnru5Ovif2KrskCx4fOD+DTkmlkgEdJE6d7vpV3jdaLWF92T/JhkbYKz2HdsCAXudOS9RfaWKhx/R8MosNRizI/l01YBiR2voEAvTrCQgtJ2mzlSNeGxGEY+PGYTtsNnb7xWXnhg0eJs17gG/QiNArTrGDSjx88yPqar9Cr8j/tAiHtmQ6gFKK4msYsOFVQYOM3IXZhx7L93tCic8SrNPs84dnXFVQshPettnlny3FlyevONQ7HV0z3SSZxGpRRHQVQz/mam1K6/BdvXuTltO4bP1CyJc/uIEYF8V7wfuVj9HAsmnMVjdxBjH2oJhCLGaxqQM8ml6EyEgmp66mwKu56yfpRFome/dMmGB0rDEW7zUjDQT4bUMxHr/TU1SHvI5fL7wZbWHUnVqC3nD1hK+cwH6WXkcyixBM6IuvY82uiUj2wM4B65k="
    jobs:
        - BUILD=DEBUG
        - BUILD=RELEASE

before_script:
    - mkdir -p BUILD/$BUILD/BUILD && cd BUILD/$BUILD/BUILD
    - |
        cmake -DCMAKE_BUILD_TYPE=$BUILD \
              -DCMAKE_INSTALL_PREFIX=.. \
              -DFTL_BUILD_TESTS=ON      \
              -DFTL_BUILD_EXAMPLES=ON   \
              ../../..

script:
    - make -j 4 && ctest --output-on-failure

