dist: bionic
sudo: false

language: c++

compiler:
    - gcc

addons:
    coverity_scan:
        project:
            name: "janweinstock/ftl"
            description: "An x86 code generator library for dynamic binary translation"
        notification_email: "jan.weinstock@rwth-aachen.de"
        build_command: "make"
        branch_pattern: "coverity"

env:
    global:
        - secure: "TUn8mnEDv5tXpwS3xDYXiomVmsGI1ON/qKVmJSwBZvmIcNJ3YXhpRzVROYUQwnPZ5D4jtpKsUP6SAhK1M0H3IiAVIfnV5V4RCsV9o2Rux6OrTSa5g0u+KLyrwSSNeFje/k8lJtG9Fro6yvhvdn9gqbeN8RIyR1cSfM6iMpLcfpQ="
    jobs:
        - BUILD=DEBUG
        - BUILD=RELEASE

before_script:
    - mkdir -p BUILD/$BUILD/BUILD && cd BUILD/$BUILD/BUILD
    - |
        cmake -DCMAKE_BUILD_TYPE=$BUILD \
              -DCMAKE_INSTALL_PREFIX=.. \
              -DFTL_BUILD_TESTS=ON      \
              -DFTL_BUILD_EXAMPLES=ON   \
              ../../..

script:
    - make -j 4 && ctest --output-on-failure

